config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'messages', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true, length: { minimum: 3, maximum: 15 }
  has_secure_password

  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:alert] = 'You must be logged in to perform this action'
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @messages = Message.includes(:user).custom_display
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    ActionCable.server.broadcast 'chatroom_channel', { new_message: message_render(message) } if message.save
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render_to_string partial: 'chatroom/message', locals: { message: message }
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new

  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'You are successfully logged in'
      redirect_to root_path
    else
      flash.now[:error] = 'There is something wrong with the login information'
      render action: :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have successfully logged out'
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = 'You are already logged in'
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/_message.html.haml
.event
  .content
    .summary
      %em= "#{message.user.username}: "
      = message.body

app/views/chatroom/index.html.haml
%h4.ui.center.aligned.medium.icon.header
  %i.circular.wechat.icon.app_color
  Say Something

.ui.two.column.grid
  .twelve.wide.column
    .ui.fluid.raised.card.chatbox
      .content#messages_content
        .ui.feed#messages_chat
          = render partial: 'message', collection: @messages

      .extra.content
        = form_for @message, html: { class: 'ui reply form' }, url: messages_path, local: false do |f|
          .field
            .ui.fluid.icon.input
              = f.text_field :body, placeholder: 'Enter a message'
              %i.bordered.inv_app_color.edit.icon.link.send_message

  .four.wide.column
    .ui.fluid.raised.card.chatbox
      .content
        .ui.inverted.vertical.menu
          %a.active.item
            Home
          %a.item
            Messages
          %a.item
            Friends

app/views/layouts/_messages.html.haml
- flash.each do |message_type, message_content|
  .ui.message.transition{class: message_type}
    %i.close.icon
    .header= message_content

app/views/layouts/_navigation_bar.html.haml
= link_to 'Chatroom', root_path, class: 'item'

%a.item
  Messages
.right.menu
  .ui.dropdown.item
    Account
    %i.dropdown.icon
    .menu
      = link_to 'Logout', logout_path, data: { turbo_method: :delete }, class: 'item' if logged_in?
      = link_to 'Login', login_path, class: 'item' unless logged_in?
  .item
    = link_to 'Login', login_path, class: 'ui primary button' unless logged_in?

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= MessagesApp
    = favicon_link_tag 'messages-favicon.ico'
    %meta{name: "viewport", content: "width=device-width,initial-scale=1"}
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "application", "data-turbo-track": "reload", media: "all"
    = javascript_importmap_tags

  %body
    .ui.small.inverted.menu
      .ui.container
        = render partial: 'layouts/navigation_bar'
    .ui.container{data: {controller: "chatroom #{params[:controller]}"}}
      = render partial: 'layouts/messages'
      = yield